version: "3.9"

services:
  backend:
    container_name: backend
    image: backend-compose-kupipodary
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  frontend:
    container_name: frontend
    image: frontend-compose-kupipodary
    networks:
      - app-network
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
