version: '3.9'

services:     
  backend:
    container_name: backend
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
      - 443:3000
    volumes:
      - ./src:/var/www/backend/src
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local